apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: adp-portal-docs-external
  annotations:
    github.com/project-slug: defra-adp-sandpit/techdocs-external
    backstage.io/techdocs-ref: dir:.

spec:
  type: documentation
  lifecycle: experimental
  owner: FCP Grants
